conventions:
    #used to override the conventions specified in Conventions\Defaults.ps1
    #convention key: value
    #framework: "3.5x64"

copyContents:
    #used to copy files or folders to certain locations prior to package
    #source folder or file:  destination folder
    #can use conventions $buildPath, $rootDir here
    # "$buildPath/project.dll":   "$buildPath/project"
    # "$buildPath/project.pdb":   "$buildPath/project"
    # "$buildPath/test":      "$buildPath/project"

packageContents:
    "$buildPath/_PublishedWebsites/ydeliver-mvc4/*":  "web.zip"

nugetSpecs:     #[project.nuspec]
    #used to specify the nuspecs to create packages out of
    #will recursiveley search the project directory to find the specified files