#common environment configuration
config:


roles:
    web:
        applications:
            ydeliver-mvc4:
                config:
        artifacts:
            web.zip:
                teamcity-build-id:   "bt2"
                auth:                "guest"

        servers:        ["localhost"]