config:
    teamcity-server:    "http://localhost:8153"

roles:
    web:
        applications:
            ydeliver-mvc4:
                config:
        artifacts:
            web.zip:
                teamcity-build-id:  "bt2"
                # path: "C:\\artifacts"

        servers:    ["localhost"]
        # credential:
        #     username:   "$env:ENV_USER_NAME"
        #     password:   "$env:ENV_PASSWORD"